config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "cats#index"

  resources :cats, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
require 'action_view'
require 'action_view/helpers'

class Cat < ApplicationRecord
    include ActionView::Helpers::DateHelper

    CAT_COLORS = ['black', 'white', 'grey', 'chocolate', 'cream']

    validates :birth_date, :color, :name, :sex, presence: true
    validates :color, inclusion: {in: CAT_COLORS }
    validates :sex, inclusion: {in: %w(M F)}
    validate :birth_date_cannot_be_future


    def birth_date_cannot_be_future
        parsed = DateTime.parse(birth_date.to_s)
        yr = parsed.year
        month = parsed.month
        day = parsed.day

        if Date.today < birth_date
            errors.add(:birth_date, "cannot be in the future...")
        elsif !Date.valid_date?(yr, month, day)
            errors.add(:birth_date, "invalid date...")
        end
    end

    def age
        time_ago_in_words(birth_date)
    end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new 
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else 
      render :new 
    end 
  end
  
  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit 
  end


  def update
    @cat = Cat.find_by(id: params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat.id)
    else 
      render :edit 
    end 
  end

  

  private
  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cats/_form.html.erb
<% if action == :new %>
    <h2>New Cat Form</h2>
<% else %>
    <h2>Edit Cat Form</h2>
<% end %>

<% action_form = action == :new ? cats_url : cat_url(@cat) %>
<% submit = action == :new ? 'Submit' : 'Edit' %>

<form action="<%= action_form %>" method="POST">
    <% if action == :edit %>
    <input type='hidden' name="_method" value="PATCH">
    <% end %>

    <label for='name'>Name:</label>
    <input id='name' type="text" name="cat[name]" value="<%= cat.name %>" placeholder="cat.name"/><br />

    <label for='birth'>Birth_date</label>
    <input id='birth' required type="date" name="cat[birth_date]" value="<%= cat.birth_date %>" placeholder="cat.birth_date"/><br />
    
    <% if cat.sex == 'M' %>
    <input type="radio" id='male' name="cat[sex]" value="M" checked />
    <% else %>
    <input type="radio" id='male' name="cat[sex]" value="M" />
    <% end %>
    <label for='male'>M</label><br>
    <% if cat.sex == 'F' %>
    <input type="radio" id='male' name="cat[sex]" value="F" checked />
    <% else %>
    <input type="radio" id='male' name="cat[sex]" value="F" />
    <% end %>
    <label for='male'>F</label><br>

    <label for="color">Color:</label>
    <select name="cat[color]" id="color" autofocus >  
    <option disabled selected><%=cat.color%></option>
    <% Cat::CAT_COLORS.each do |color| %> 
        <% if cat.color == 'F' %>
        <option value="<%=color%>"> <%=color%> selected</option>
        <% else %>
        <option value="<%=color%>"> <%=color%> </option>
        <% end %>
    <% end %>
    
    </select><br>

    <label for="description">Description</label>
    <textarea name="cat[description]" value=""><%=@cat.description%></textarea>


    <input type="submit" value=<%= submit %> />
</form>

app/views/cats/edit.html.erb
<%= render 'form', cat: @cat, action: :edit %>

app/views/cats/index.html.erb
<h2>Cats Index</h2>


<% @cats.each do |cat| %>
  <ul>
    <li><a href="<%= cat_url(cat.id) %>">Name: <%= cat.name %></a></li>
    <li>Birth Date: <%= cat.birth_date %></li>
    <li>Color: <%= cat.color %></li>
    <li>Sex: <%= cat.sex %></li>
    <li>Description: <%= cat.description %></li>
  </ul>
<% end %>

<h4><a href="<%= new_cat_url %>">Add New Cat</a></h4>

app/views/cats/new.html.erb
<%= render 'form', cat: @cat, action: :new %>

app/views/cats/show.html.erb
<h2><%= @cat.name %></h2>
  <ul>
    <li>Birth Date: <%= @cat.birth_date %></li>
    <li>Color: <%= @cat.color %></li>
    <li>Sex: <%= @cat.sex %></li>
    <li>Description: <%= @cat.description %></li>
    
  </ul>
  <h5><a href="<%= edit_cat_url(@cat) %>">Update Info</a></h5> 
  <h6><a href="<%= cats_url %>" />Back to All Cats</h6> 
   
  

   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>